name: history_collab
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  code_text_field: ^1.1.0
  flutter: 
    sdk: flutter
  github: ^9.24.0
  pretty_diff_text: ^2.0.0
  firebase_core: ^3.1.1
  firebase_database: ^11.0.2
  firebase_remote_config: ^5.0.2
  get: ^4.6.6
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: SourceCode
      fonts:
        - asset: assets/fonts/sourceCode/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/sourceCode/SourceCodePro-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/sourceCode/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/sourceCode/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/sourceCode/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sourceCode/SourceCodePro-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/sourceCode/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/sourceCode/SourceCodePro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/sourceCode/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/sourceCode/SourceCodePro-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/sourceCode/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/sourceCode/SourceCodePro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLightItalic.ttf
          style: italic
          weight: 200

  # assets:
  #   - assets/
  #   - assets/articles/
