// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvbBomxT3DlrJ9wE1snv3CWX8UEWW-LkQ',
    appId: '1:71915597486:web:022ab10391181675f8073f',
    messagingSenderId: '71915597486',
    projectId: 'history-collab',
    authDomain: 'history-collab.firebaseapp.com',
    storageBucket: 'history-collab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMPEf4eLivEY4fsERrVFaYhH1rjVgDTiY',
    appId: '1:71915597486:android:f9e6e23ab8d48677f8073f',
    messagingSenderId: '71915597486',
    projectId: 'history-collab',
    storageBucket: 'history-collab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv02AG_8m8VchLXlloM18tmEzkRRKkx-Y',
    appId: '1:71915597486:ios:283e3c75fa812975f8073f',
    messagingSenderId: '71915597486',
    projectId: 'history-collab',
    storageBucket: 'history-collab.appspot.com',
    iosClientId: '71915597486-5fqv6b1a282j4ck44fhvgnc064e232g9.apps.googleusercontent.com',
    iosBundleId: 'com.arrijal.historyCollab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv02AG_8m8VchLXlloM18tmEzkRRKkx-Y',
    appId: '1:71915597486:ios:283e3c75fa812975f8073f',
    messagingSenderId: '71915597486',
    projectId: 'history-collab',
    storageBucket: 'history-collab.appspot.com',
    iosClientId: '71915597486-5fqv6b1a282j4ck44fhvgnc064e232g9.apps.googleusercontent.com',
    iosBundleId: 'com.arrijal.historyCollab',
  );
}
